// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YJYQ-JsGHVc8K5JbHCZR3tlh7MVaTP0',
    appId: '1:997037383909:android:00b99f46de58e543fd340c',
    messagingSenderId: '997037383909',
    projectId: 'do-save-mn',
    databaseURL: 'https://do-save-mn-default-rtdb.firebaseio.com',
    storageBucket: 'do-save-mn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO9XxtPolstzhuLewXJR_JCiFRtdDIODk',
    appId: '1:997037383909:ios:bd4e447387edb882fd340c',
    messagingSenderId: '997037383909',
    projectId: 'do-save-mn',
    databaseURL: 'https://do-save-mn-default-rtdb.firebaseio.com',
    storageBucket: 'do-save-mn.firebasestorage.app',
    iosClientId: '997037383909-sk1j2vqhu73g2e93pkipuvdm14v9tero.apps.googleusercontent.com',
    iosBundleId: 'com.example.doSaveMoney.RunnerTests',
  );

}